In [2]:
# Import pustaka dan class yang dibutuhkan
import seaborn as sns
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.preprocessing import LabelEncoder

penguins = sns.load_dataset("penguins")
print(penguins.head())

penguins = penguins.dropna()

X = penguins[["bill_length_mm", "bill_depth_mm",
              "flipper_length_mm", "body_mass_g"]]

label = LabelEncoder()
y = label.fit_transform(penguins["species"])

print(label.classes_)   # memberi tahu urutan label

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

cm = confusion_matrix(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)

print("\nConfusion Matrix:")
print(cm)

print("\nAkurasi Model:", acc)

data_baru = [[45.7, 18.5, 200.0, 4200]]    # contoh data baru

data_baru_scaled = scaler.transform(data_baru)

hasil = knn.predict(data_baru_scaled)
hasil_asli = label.inverse_transform(hasil)

print("\nPrediksi spesies untuk data baru:", hasil_asli[0])


  species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female  
['Adelie' 'Chinstrap' 'Gentoo']

Confusion Matrix:
[[48  0  0]
 [ 1 17  0]
 [ 0  0 34]]

Akurasi Model: 0.99

Prediksi spesies untuk data baru: Adelie


c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [3]:
# ----------------------------------------------------
# Import pustaka dan class yang dibutuhkan
# ----------------------------------------------------
import seaborn as sns
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.preprocessing import LabelEncoder

# ----------------------------------------------------
# Load dataset penguins
# ----------------------------------------------------
penguins = sns.load_dataset("penguins")
print(penguins.head())

# Menghapus record yang berisi NaN
penguins = penguins.dropna()

# Memilih atribut dataset
X = penguins[["bill_length_mm", "bill_depth_mm", 
              "flipper_length_mm", "body_mass_g"]]

y = penguins["species"]

# Encode target class (string → angka)
label = LabelEncoder()
y = label.fit_transform(y)

print(label.classes_)

# ----------------------------------------------------
# Lanjutkan kode berikut
# ----------------------------------------------------

# 1. Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 2. Standarisasi data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 3. Membangun model KNN
model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train_scaled, y_train)

# 4. Prediksi data test
y_pred = model.predict(X_test_scaled)

# 5. Hitung Confusion Matrix & Akurasi
cm = confusion_matrix(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)

print("\n=== CONFUSION MATRIX ===")
print(cm)

print("\n=== AKURASI MODEL ===")
print(f"Akurasi: {acc * 100:.2f}%")

# ----------------------------------------------------
# 6. Prediksi KNN dengan data baru
# ----------------------------------------------------
data_baru = np.array([[50, 15, 210, 4200]])   # contoh input manual
data_baru_scaled = scaler.transform(data_baru)

hasil = model.predict(data_baru_scaled)
hasil_species = label.inverse_transform(hasil)

print("\n=== PREDIKSI DATA BARU ===")
print(f"Prediksi spesies: {hasil_species[0]}")


  species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female  
['Adelie' 'Chinstrap' 'Gentoo']

=== CONFUSION MATRIX ===
[[31  0  0]
 [ 0 13  0]
 [ 0  0 23]]

=== AKURASI MODEL ===
Akurasi: 100.00%

=== PREDIKSI DATA BARU ===
Prediksi spesies: Gentoo


c:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [4]:
from sklearn.metrics import confusion_matrix, accuracy_score
# Menghitung confusion matrix dan akurasi
cm = confusion_matrix(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)

print("\n=== CONFUSION MATRIX ===")
print(cm)
print("\n=== SKOR AKURASI ===")
print(f"Akurasi Model: {acc * 100:.2f}%")
# Penjelasan
print("\n=== PENJELASAN ===")
print("Confusion matrix adalah tabel evaluasi yang menunjukkan jumlah prediksi benar dan salah "
      "untuk setiap kelas.\n nilai pada diagonal berarti prediksi benar, sedangkan nilai di luar diagonal "
      "menunjukkan kesalahan prediksi antar kelas.")

print("\nAkurasi adalah persentase prediksi yang benar dari seluruh data uji. Nilai akurasi yang tinggi "
      "menandakan bahwa model KNN mampu mengenali pola fitur secara baik.")
# Interpretasi otomatis
print("\n=== INTERPRETASI MODEL ===")
if acc >= 0.90:
    print("Model memiliki performa yang sangat baik karena sebagian besar prediksi sesuai dengan label aslinya.")
elif acc >= 0.75:
    print("Model memiliki performa yang baik, namun masih terdapat beberapa kesalahan prediksi antar kelas.")
else:
    print("Performa model kurang optimal dan memerlukan peningkatan, seperti tuning parameter atau perbaikan preprocessing.")


=== CONFUSION MATRIX ===
[[31  0  0]
 [ 0 13  0]
 [ 0  0 23]]

=== SKOR AKURASI ===
Akurasi Model: 100.00%

=== PENJELASAN ===
Confusion matrix adalah tabel evaluasi yang menunjukkan jumlah prediksi benar dan salah untuk setiap kelas.
 nilai pada diagonal berarti prediksi benar, sedangkan nilai di luar diagonal menunjukkan kesalahan prediksi antar kelas.

Akurasi adalah persentase prediksi yang benar dari seluruh data uji. Nilai akurasi yang tinggi menandakan bahwa model KNN mampu mengenali pola fitur secara baik.

=== INTERPRETASI MODEL ===
Model memiliki performa yang sangat baik karena sebagian besar prediksi sesuai dengan label aslinya.
